### PR TITLE
Updated for Rimworld 1.1

### PR DESCRIPTION
**Pull request by Jellypowered**
Hello! 

I've "updated" your mod to work with 1.1 however you'll need to evaluate the EvalHydroponicsBasins() As I called System.Obsolete to keep it working for now. I don't know enough about programming to redo that function myself. 

Thanks for looking!

### CODE REVIEW

**Comment by EbonJaeger** [comment]
I pushed a commit to this branch to "unobsolete" the one function. Before merging though, we need to find a way for it to not include all of the Unity dll's in the Assembly output.

**Comment by Jellypowered** [comment]
I'll see what I can figure out tonight! 
Edit: Figured it out, changed RePowerReborn.csproj to reflect as such. 

Let me know if anything else needs changed, thanks for the help on the EvalHydroponicBasins()

**Comment by Jellypowered** [comment]
Pretty sure that's all that needs to be changed. I updated About.xml to reflect the new inbuilt mod dependencies/sorting features as well. 

Also sorry about all the extra commits inbetween, I'm new to using github commit stuff.

**Review by EbonJaeger — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
